---

# place objects into its own namespace
namespace: reloader

resources:
- namespace.yaml
- https://github.com/stakater/Reloader/deployments/kubernetes

patches:
# use patch to remove namespace from non-namespaced objects, which would throw error
- target:
    kind: "Cluster.*|ServiceAccount.*"
  patch: |-
    - op: remove
      path: /metadata/namespace
